version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage_egas:/data
    environment:
      MINIO_ROOT_USER: egas
      MINIO_ROOT_PASSWORD: egas13160008
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}