---

- hosts: all
  tasks:
    - name: Creating an empty file
      file:
        path: "/home/hramirez/hernan.txt"
        state: touch
    - name: Add content to the file
      copy:
        content: "Este es el contenido que deseas agregar al archivo.\nOtra línea de contenido."
        dest: "/home/hramirez/hernan.txt"
