version: '3'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: egas
      POSTGRES_PASSWORD: 13160008
    volumes:
      - /root/ansible/dockers/postgres-container:/var/lib/postgresql/data
    ports:
      - "5433:5433"